### ISSUE TITLE
crypto@0.0.3: This package is no longer supported

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/borderline-server#1]
It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

**Comment by Tezirg** [comment]
#31b4cbeea9141dd423006254e42254c0a53d243a removes the dependency.
No code change needed because the HMAC interface API unchanged, subsequent testing confirm it's all good. 

Will close when it reaches master

**Comment by Tezirg** [comment]
Ok, this has reached master. Closing.
